backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Info"
    name: "info"
    files:
      - label: "Opening hours"
        name: "opening_hours"
        file: "src/_data/opening_hours.yaml"
        fields:
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Special", name: "special", widget: "markdown" }
          - { label: "Special before?", name: "special_before", widget: "boolean" }
          - label: "Opening hours"
            name: times
            widget: list
            allow_add: true
            fields:
              - { label: "Day(s)", name: "day", widget: string }
              - { label: "Hours", name: "time", widget: string }
      - label: "Find us"
        name: "find_us"
        file: "src/_data/find_us.yaml"
        fields:
          - { label: "Title", name: "header", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Image", name: "image", widget: "image" }
      - label: "About"
        name: "about"
        file: "src/_data/about.yaml"
        fields:
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Photo", name: "photo", widget: "image" }
  - label: "Images"
    name: "images"
    editor:
      preview: false
    files:
      - label: "Header & logo"
        name: "header_logo"
        file: "src/_data/header_logo.yaml"
        fields:
          - { label: "Header image", name: "header_image", widget: "image" }
          - { label: "Logo", name: "logo", widget: "image" }
