backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Info"
    name: "info"
    files:
      - label: "Opening hours"
        name: "opening_hours"
        file: "src/_data/opening_hours.yaml"
        fields:
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Special before", name: "special_before", widget: "markdown", required: false }
          - { label: "Special after", name: "special_after", widget: "markdown", required: false }
          - label: "Opening hours"
            name: times
            widget: list
            allow_add: true
            fields:
              - { label: "Day(s)", name: "day", widget: string }
              - { label: "Hours", name: "time", widget: string }
      - label: "Contact us"
        name: "contact_us"
        file: "src/_data/contact_us.yaml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Phone number", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Bussiness Info", name: "text", widget: "markdown" }
          - { label: "IG Link", name: "ig", widget: "string" }
          - { label: "FB Link", name: "fb", widget: "string" }
      - label: "Find us"
        name: "find_us"
        file: "src/_data/find_us.yaml"
        fields:
          - { label: "Title", name: "header", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Image", name: "image", widget: "image" }
      - label: "About"
        name: "about"
        file: "src/_data/about.yaml"
        fields:
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Photo", name: "photo", widget: "image" }
      - label: "Feed"
        name: "feed"
        file: "src/_data/feed.yaml"
        fields:
          - { label: "Feed HTML", name: "feed", widget: "markdown" }
      - label: "Navigation"
        name: "navigation"
        file: "src/_data/navigation.yaml"
        fields:
          - label: "Links"
            name: "links"
            widget: list
            allow_add: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
      - label: "Lamp shades"
        name: "lamp_shades"
        file: "src/_data/lampshades.yaml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Button text", name: "button", widget: "string" }
          - { label: "Sizes", name: "sizes", widget: "markdown" }
          - label: "Images"
            name: "images"
            widget: list
            allow_add: true
            fields:
              - { label: "Image", name: "image", widget: "image" }
      - label: "Handelsbetingelser"
        name: "handel"
        file: "src/_data/handel.yaml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
  - label: "Images"
    name: "images"
    editor:
      preview: false
    files:
      - label: "Header & logo"
        name: "header_logo"
        file: "src/_data/header_logo.yaml"
        fields:
          - { label: "Header image", name: "header_image", widget: "image" }
          - { label: "Logo", name: "logo", widget: "image" }
